x-default-logging:
  &logging
  driver: "json-file"
  options:
    max-size: "3m"
    max-file: "1"

services:
  lgtm:
    image: grafana/otel-lgtm:0.11.7
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP gRPC
      - "9464:9464"   # Prometheus metrics
    logging: *logging
    volumes:
      - ./docker/otel-collector/config.yml:/otel-lgtm/otelcol-config.yaml
      - lgtm-grafana:/data/grafana
      - lgtm-prometheus:/data/prometheus
      - lgtm-loki:/data/loki
      - lgtm-tempo:/data/tempo
    networks:
      - outbox-pattern

  promtail:
    image: grafana/promtail:3.0.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./docker/promtail/config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    logging: *logging
    depends_on:
      - lgtm
    networks:
      - outbox-pattern

volumes:
  lgtm-grafana:
  lgtm-prometheus:
  lgtm-loki:
  lgtm-tempo:

networks:
  outbox-pattern:
    name: outbox-pattern-network
