openapi: 3.0.1
info:
  version: 0.1.0
  title: Outbox Pattern API
  description: >-
    Outbox Pattern API
  license:
    url: https://opensource.org/licenses/MIT
    name: MIT
security: []
servers:
  - url: /
paths:
  /api/v1/products:
    $ref: './paths/v1/products.yml'
